### ISSUE TITLE
GROUP RUBY CAPSTONE PROJECT

### ISSUE THREAD

**Issue by mosidrum** [anita00001/Catalog-of-my-things#24]
https://github.com/anita00001/Catalog-of-my-things/projects/1

**We are two members in this group**
@anita00001 is team member 1 and was assigned task listed for team member 1
@mosidrum is team member 2 and was assign task listed for team member 2

**Comment by julie-ify** [comment]
Hi @mosidrum and @anita00001,

## Highlights!
- Evenly distributed tasks ✔️
- Descriptive issue ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
